### ISSUE TITLE
Not Saving the Keychain or fetch when debugger connected to Device and Fetched value. IOS9

### ISSUE THREAD

**Issue by vicky1787** [jeremangnr/JNKeychain#10]
Not Saving the Keychain or fetch when debugger connected to Device and Fetched value. IOS9

**Comment by vicky1787** [comment]
Hello Jeremias,

Please can you look into this, when I have to run the app in Debug mode and  IOS 9.2 update I sometimes don't see the keychain saved and read successfully.

I tested this happens only when its in debug and in release all is okay on Device.

**Comment by jeremangnr** [comment]
Hi @vickyrappier, sorry for the delay. I'll have a look this week and get back to you.

**Comment by vicky1787** [comment]
Thanks a lot.

On Tuesday, 12 January 2016, Jeremias Nunez notifications@github.com
wrote:

> Hi @vickyrappier https://github.com/vickyrappier, sorry for the delay.
> I'll have a look this week and get back to you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jeremangnr/JNKeychain/issues/10#issuecomment-170922920
> .

## 

Sent from my iPhone

**Comment by vicky1787** [comment]
Hi Jeremias,

Did you find this issue. Any help over this please. As our app is not able to be debugged as always the keychain value generated and sent to server is never getting saved in DEBUG mode.

Please help :)

**Comment by Nicolas-Isaza** [comment]
Running into the same problem.

**Comment by vicky1787** [comment]
Hello Jeremias,

Can you help out if you figured this issue please , needed quick advice or suggestive library that can have a temporary fix for this issue as the app is in production.

**Comment by jeremangnr** [comment]
Do you see any errors logged on the console while debugging @vickyrappier?

**Comment by jeremangnr** [comment]
@vickyrappier @Nicolas-Isaza as referenced in #11, this is a known issue
