### ISSUE TITLE
Keychain error -34018

### ISSUE THREAD

**Issue by Ruckt** [jeremangnr/JNKeychain#11]
On occasion, when trying to access or write to the keychain, an error occurs and I'm unable to use the keychain.  The error number of CHECK_OSSTATUS_ERROR(result) is -34018.  This happens on the iPhone 5S, no the 6S.  Both are on iOS 9.2.

**Comment by AnilJifflenow** [comment]
Hi Even I am facing same issue.
Any workaround ?

**Comment by jeremangnr** [comment]
@Ruckt @AnilJifflenow this seems to be a known issue with the Keychain itself

http://stackoverflow.com/questions/27752444/ios-keychain-writing-value-results-in-error-code-34018
https://github.com/soffes/sskeychain/issues/52
