### ISSUE TITLE
Cloning Repo to run example project

### ISSUE THREAD

**Issue by rajohns08** [jeremangnr/JNKeychain#5]
When I clone repo and run 'pod install' from the example directory, I get:

Fetching podspec for `JNKeychain` from `../`
[!] Unable to satisfy the following requirements:

- `JNKeychain (from `../`)` required by `Podfile`
- `JNKeychain (from `../`)` required by `Podfile`
- `JNKeychain (= 0.1.0)` required by `Podfile.lock`

**Comment by jeremangnr** [comment]
Hey, thanks for the report. I fixed this and pushed a new podspec, so you should be able to do a `pod install` on the `Example` directory now. If for some reason that doesn't work, `pod update` will do the trick

**Comment by ludm** [comment]
Hello I have added the line 
pod "JNKeychain"
 in my pod file but when I run 
pod install or pod update, I have the message:
[!] Unable to satisfy the following requirements:

- `JNKeychain` required by `Podfile`
Do I need to copy specific files?
